In [ ]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df=pd.read_csv('hous_price_multivarient.csv')
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
#missing values
df.bedrooms.median()

4.0

In [ ]:
df.bedrooms=df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
df.bedrooms=df.bedrooms.astype(int)
df

area  bedrooms  age   price
0  2600         3   20  550000
1  3000         4   15  565000
2  3200         4   18  610000
3  3600         3   30  595000
4  4000         5    8  760000
5  4100         6    8  810000

In [ ]:
new_df=df.drop('price',axis='columns')
new_df

area  bedrooms  age
0  2600         3   20
1  3000         4   15
2  3200         4   18
3  3600         3   30
4  4000         5    8
5  4100         6    8

In [ ]:
#model:
reg=linear_model.LinearRegression()
reg.fit(new_df,df.price)

LinearRegression()

In [ ]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [ ]:
#slop
x_values=reg.coef_
x_values

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
intercept=reg.intercept_
intercept

221323.00186540396

In [ ]:
#y=mx+c
ans=np.dot(x_values,[3000,3,40])+intercept
ans

498408.2515803067

In [ ]:
#find price of 2500sg ft, 4 bedroom, 5 year old
reg.predict([[2500,4,5]])

array([578876.03748933])